apiVersion: v1
kind: ConfigMap
metadata:
  name: authorization
data:
  application.yaml: |-
    security:
      client: client
      authorizedGrantTypes:
        - authorization_code
        - password
      scopes: user_info
      redirectUris:
        - http://localhost:8090/login
        - http://127.0.0.1:8200/login
        - http://localhost:8200/login
        - http://172.22.0.1:8200/login
        - http://192.168.99.100:30200/login
      password: password